# Generated by Django 3.1.14 on 2022-06-14 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220610_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
